
- name: yum安装 haproxy
  yum: name=haproxy state=latest
  become: true

- name: 创建haproxy配置目录
  file: name=/etc/haproxy state=directory
  become: true

- name: 修改centos的haproxy.service
  template: src=haproxy.service.j2 dest=/usr/lib/systemd/system/haproxy.service
  become: true

- name: 配置 haproxy
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  become: true

- name: yum安装 keepalived
  yum: name=keepalived state=latest
  become: true

- name: yum安装 psmisc
  yum: name=psmisc state=latest
  become: true

- name: 创建keepalived配置目录
  file: name=/etc/keepalived state=directory
  become: true

- name: 配置 keepalived 主节点
  template: src=keepalived-master.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "master"
  become: true

- name: 配置 keepalived 备节点
  template: src=keepalived-backup.conf.j2 dest=/etc/keepalived/keepalived.conf
  when: LB_ROLE == "slave"
  become: true

- name: daemon-reload for haproxy.service
  shell: systemctl daemon-reload
  become: true

- name: 重启haproxy服务
  shell: systemctl enable haproxy && systemctl restart haproxy
  become: true

- name: 重启keepalived服务
  shell: systemctl enable keepalived && systemctl restart keepalived
  become: true
