---
- include: ../facts/common.yml
- include: ../facts/etcd.yml
- include: ../facts/kubernetes.yml

- name: deploy kubernetes nodes
  hosts: kubernetes-node
  roles:
  - docker-overlay  #这里的两种docker安装方式二选一
  - k8s-node
  tags: node-scale

#- name: run calico network policy
#  hosts: kubernetes-master
#  roles:
#  - calico